version: 2
project_name: git-gud

builds:
  - id: git-gud
    main: ./cmd/git-gud
    binary: git-gud
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.buildVersion=v{{ .Version }}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: git-gud-archive
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - id: syft-json
    artifacts: archive
    cmd: syft
    args:
      - "$artifact"
      - "-o"
      - "cyclonedx-json=$document"

snapshot:
  version_template: "{{ incpatch .Version }}-next+{{ .ShortCommit }}"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: igor-makarov
    name: git-gud
  draft: false
  prerelease: auto
  mode: replace
